# Generated by Django 5.2.17 on 2026-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vocabulary_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_Type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in Blank'), ('listening', 'Listening')], default='multiple_choice', max_length=20),
        ),
    ]
